#!/usr/bin/bash
PID=$(pgrep -x sleeptimer)
if [ $PID != $$ ]; then
	kill -9 $PID &> /dev/null
fi
if [ $# -eq 0 ]; then
	SLEEP=3600
else
	SLEEP=$(($1*60))
fi
# Notify user every 10 minutes how much time is left
STEP=600
if [ $STEP -gt $SLEEP ]; then
	STEP=$SLEEP
fi
CURRENT=$SLEEP
while [ $CURRENT -gt 0 ] 
do
	TIME_LEFT=$(($CURRENT/60))
	if [ $TIME_LEFT -eq 1 ]; then
		echo "Suspending system in 1 minute..."
		notify-send "Sleeptimer" "Suspending system in 1 minute..."
	else
		echo "Suspending system in $TIME_LEFT minutes..."
		notify-send "Sleeptimer" "Suspending system in $TIME_LEFT minutes..."
	fi
	sleep $STEP
	CURRENT=$(($CURRENT-$STEP))
done
echo "Sleeptimer" "Suspending system"
systemctl suspend
